### ISSUE TITLE
Styling the Home page using CSS

### ISSUE THREAD

**Issue by Kashish-mogha26** [Kashish-mogha26/App-Development-MERN#4]
Make different classes in CSS and give them different properties like font, color, margins, etc.  Refer to the JS files in the repo to look for the layout. Upload the CSS file.

**Comment by raji2004** [comment]
please assign me this issue

**Comment by Im-Kunal-13** [comment]
@Kashish-mogha26 I would like to work on this issue. Can you assign this to me?

**Comment by VaibhavMogha** [comment]
Assign this issue to me.
